name: auth_module
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  connectivity_plus: 4.0.2
  dartz: 0.10.1
  flutter_screenutil: 5.8.4
  flutter_bloc: 8.1.3
  flutter_riverpod: 2.4.0
  equatable: 2.0.5
  get_it: 7.6.0
  dio: 5.1.1
  pretty_dio_logger: 1.3.1
  logger: 1.1.0
  network:
    path: ./modules/network
  shared_preferences: 2.2.0
  flutter_svg: 2.0.7
  intl: 0.18.1
  fluttertoast: 8.2.2
  webview_flutter: 4.2.2
  webview_flutter_android: 3.8.1
  webview_flutter_wkwebview: 3.6.1
  firebase_core: 2.15.0
  device_info_plus: 9.0.1
  firebase_messaging: 14.6.5
  firebase_crashlytics: 3.3.4
  flutter_local_notifications: 15.1.0+1
  firebase_analytics: 10.4.4
  image_picker: 1.0.2
  permission_handler: 11.0.0
  country_code_picker: 3.0.0
  flutter_image_compress: 2.0.4

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/auth_configure/

  fonts:
    - family: Caros
      fonts:
        - asset: assets/fonts/Caros-Bold.otf
          weight: 700
        - asset: assets/fonts/Caros-Medium.otf
          weight: 500

    - family: Circular
      fonts:
        - asset: assets/fonts/Circular-Medium.ttf
          weight: 500
