// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmaJ0wS34SRNP6oCJwIQ8YYu8GdVePe9Y',
    appId: '1:657622832573:web:f08dba3b5abc2416dfeed4',
    messagingSenderId: '657622832573',
    projectId: 'boilerplate-authenticati-17496',
    authDomain: 'boilerplate-authenticati-17496.firebaseapp.com',
    storageBucket: 'boilerplate-authenticati-17496.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeTzwdM_VBs0hTIb_sn86UxLEYI6li8bU',
    appId: '1:657622832573:android:6c692aa88da4bc03dfeed4',
    messagingSenderId: '657622832573',
    projectId: 'boilerplate-authenticati-17496',
    storageBucket: 'boilerplate-authenticati-17496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZvZ0B55FDDS21USQeFUcFLBI6jklq4k',
    appId: '1:657622832573:ios:c9d399a512281efbdfeed4',
    messagingSenderId: '657622832573',
    projectId: 'boilerplate-authenticati-17496',
    storageBucket: 'boilerplate-authenticati-17496.appspot.com',
    iosBundleId: 'com.brainstation23.authentication',
  );
}
